project_name: test-results

before:
  hooks:
    - go generate ./...

builds:
  - id: non-windows-build
    env:
    - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: windows-build
    env:
    - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.VERSION={{.Tag}}
    goos:
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64

archives:
  - id: non-windows-archive
    builds:
      - non-windows-build
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: windows-archive
    builds:
      - windows-build
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
