on: [push]
name: Unit tests
jobs:
  unit-testing:
    runs-on: windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          go get ./...
          go get -u gotest.tools/gotestsum
          gotestsum --junitfile /tmp/junit.xml