on: [push]
name: Unit tests
jobs:
  unit-testing:
    runs-on: windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          go get ./...
          go install gotest.tools/gotestsum@latest
          gotestsum --format short-verbose --packages="./..." -- -p 1